//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFacturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLEMPLEADO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLEMPLEADO()
        {
            this.TBLFACTURA = new HashSet<TBLFACTURA>();
            this.TBLSEGURIDAD = new HashSet<TBLSEGURIDAD>();
        }
    
        public int IdEmpleado { get; set; }
        public string strNombre { get; set; }
        public long NumDocumento { get; set; }
        public string StrDireccion { get; set; }
        public string StrTelefono { get; set; }
        public string StrEmail { get; set; }
        public Nullable<int> IdRolEmpleado { get; set; }
        public Nullable<System.DateTime> DtmIngreso { get; set; }
        public Nullable<System.DateTime> DtmRetiro { get; set; }
        public string strDatosAdicionales { get; set; }
        public Nullable<System.DateTime> DtmFechaModifica { get; set; }
        public string StrUsuarioModifico { get; set; }
    
        public virtual TBLROLES TBLROLES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLFACTURA> TBLFACTURA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLSEGURIDAD> TBLSEGURIDAD { get; set; }
    }
}
