//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCFacturacion.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLFACTURA
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TBLFACTURA()
        {
            this.TBLDETALLE_FACTURA = new HashSet<TBLDETALLE_FACTURA>();
        }
    
        public int IdFactura { get; set; }
        public Nullable<System.DateTime> DtmFecha { get; set; }
        public int IdCliente { get; set; }
        public int IdEmpleado { get; set; }
        public Nullable<double> NumDescuento { get; set; }
        public Nullable<double> NumImpuesto { get; set; }
        public Nullable<double> NumValorTotal { get; set; }
        public Nullable<int> IdEstado { get; set; }
        public Nullable<System.DateTime> DtmFechaModifica { get; set; }
        public string StrUsuarioModifica { get; set; }
    
        public virtual TBLCLIENTES TBLCLIENTES { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TBLDETALLE_FACTURA> TBLDETALLE_FACTURA { get; set; }
        public virtual TBLEMPLEADO TBLEMPLEADO { get; set; }
        public virtual TBLESTADO_FACTURA TBLESTADO_FACTURA { get; set; }
    }
}
